version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    image: mobilise-digital:latest
    ports:
      - "3000:3000"
    depends_on:
      - db
