default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] %>
  username:  <%= ENV['DB_USERNAME'] %>
  password:  <%= ENV['DB_PASSWORD'] %>
  pool: 5

development:
  <<: *default
  database: mobilise-digital_development
  host:  <%= ENV['DB_HOST'] %>

production:
  <<: *default
  database: mobilise-digital_production

